data<-read.table("household_power_consumption.txt", sep=";",header=TRUE, dec=".",na.string="?")
data1<-data[(data$Date=="1/2/2007"|data$Date=="2/2/2007"),]
Sys.setlocale("LC_TIME",locale="English")
library(lubridate)
dt<-dmy(data1$Date)
dt1<-hms(data1$Time)
tt<-update(dt,hours=hour(dt1), minutes=minute(dt1), seconds=0)
png(file="plot4.png")
par(mfrow=c(2,2))
plot(tt,data1$Global_active_power,type=("l"),xlab="" , ylab="Global Active Power [KWh]")
plot(tt,data1$Voltage,type=('l'),xlab="datetime", ylab="Voltage")
plot(tt,data1$Sub_metering_1,type=("l"),xlab="" , ylab="Energy Sub metering")
lines(tt,data1$Sub_metering_2, col="red")
lines(tt,data1$Sub_metering_3, col="blue")
legend("topright",legend=c( "Sub_Metering_1","Sub_Metering_2","Sub_Metering_3"),lty=1, col=c("black","red","blue"), xjust=0.1, yjust=0.1,box.lwd=0 )
plot(tt, data1$Global_reactive_power, type=("l"),xlab="datetime",ylab="Global Rective Power")
dev.off()